"""
Parses the TEI-XML files generated by GROBID and extracts cleanly structured text: title, abstract, and sections (including headings).

References are not extracted (as they are irrelevant to the analysis).

Output per paper, depending on the --mode setting:
- <name>.json         -> Always generated; structured (title, abstract, sections: `[{heading, text}]`)
- <name>.txt          -> With --mode full: complete body text
- <name>.compact.txt  -> With --mode compact: abstract plus Introduction/Conclusion-style sections only
"""

import argparse
import json
from pathlib import Path

from lxml import etree
from tqdm import tqdm

TEI_NS = {"tei": "http://www.tei-c.org/ns/1.0"}

COMPACT_SECTION_KEYWORDS = [
    "introduction",
    "background",
    "motivation",
    "problem statement",
    "einleitung",
    "einführung",
    "hintergrund",
    "problemstellung",
    "conclusion",
    "discussion",
    "summary",
    "results",
    "gaps",
    "future work",
    "limitation",
    "concluding remarks",
    "final remarks",
    "fazit",
    "zusammenfassung",
    "diskussion",
    "schlussfolgerung",
    "ausblick",
    "limitationen",
]


def is_relevant_for_compact(heading: str) -> bool:
    """Checks via keyword matching whether a section is relevant for the compact version."""
    if not heading:
        return False
    heading_lower = heading.lower()
    return any(keyword in heading_lower for keyword in COMPACT_SECTION_KEYWORDS)


def get_text(el) -> str:
    """Collects all text from an element, including nested children, and normalizes whitespace."""
    if el is None:
        return ""
    text = " ".join(el.itertext())
    return " ".join(text.split())


ACKNOWLEDGEMENT_KEYWORDS = ["acknowledg", "danksagung", "dank an"]


def is_acknowledgement(div, heading: str) -> bool:
    """Identifies acknowledgements sections via the TEI `type` attribute or heading (DE/EN)."""
    if div.get("type", "").lower() == "acknowledgement":
        return True
    heading_lower = heading.lower()
    return any(keyword in heading_lower for keyword in ACKNOWLEDGEMENT_KEYWORDS)


def extract_sections(container) -> list:
    """Collects sections (heading + paragraphs) from a TEI container (<body> or <back>).

    Divs containing a reference list (<listBibl>) are skipped—this reliably
    excludes the bibliography, regardless of whether it appears as a separate
    section in the <back> or is named differently. Acknowledgments are also
    excluded, as they are irrelevant in terms of content.
    """
    sections = []
    if container is None:
        return sections

    for div in container.findall(".//tei:div", TEI_NS):
        if div.find(".//tei:listBibl", TEI_NS) is not None:
            continue  # irrelevant

        head_el = div.find("tei:head", TEI_NS)
        heading = get_text(head_el) if head_el is not None else ""

        if is_acknowledgement(div, heading):
            continue  # irrelevant

        paragraphs = []
        for p in div.findall("tei:p", TEI_NS):
            p_text = get_text(p)
            if p_text:
                paragraphs.append(p_text)

        section_text = "\n".join(paragraphs)
        if (
            section_text
        ):  # Skip empty sections (e.g., those containing only figure containers).
            sections.append({"heading": heading, "text": section_text})

    return sections


def parse_tei(xml_path: Path) -> dict:
    tree = etree.parse(str(xml_path))

    title_el = tree.find(".//tei:titleStmt/tei:title", TEI_NS)
    title = get_text(title_el)

    abstract_el = tree.find(".//tei:abstract", TEI_NS)
    abstract = get_text(abstract_el)

    # <body> contains the main body.
    # Some PDFs/GROBID parses place sections such as Conclusions, Acknowledgments,
    # or Appendices into the <back> instead—this is captured here,
    # though the reference list contained within them is specifically excluded (see extract_sections).
    body = tree.find(".//tei:text/tei:body", TEI_NS)
    back = tree.find(".//tei:text/tei:back", TEI_NS)
    sections = extract_sections(body) + extract_sections(back)

    return {
        "title": title,
        "abstract": abstract,
        "sections": sections,
    }


def to_plain_text(parsed: dict, compact: bool = False) -> str:
    """Constructs the final running text for the LLM prompt from the structured dictionary.

    compact=True: includes only the abstract and sections with headings matching
    Introduction/Background/Conclusion/Discussion or similar (see COMPACT_SECTION_KEYWORDS).
    Sufficient for categorization, problem statement, solution, and research gap—
    significantly fewer characters than the full version, usually enough for a single
    LLM call without chunking.
    """
    parts = []
    if parsed["title"]:
        parts.append(f"TITEL: {parsed['title']}")
    if parsed["abstract"]:
        parts.append(f"\nABSTRACT:\n{parsed['abstract']}")

    sections = parsed["sections"]
    if compact:
        sections = [s for s in sections if is_relevant_for_compact(s["heading"])]

    for sec in sections:
        heading = sec["heading"] or "(ohne Überschrift)"
        parts.append(f"\n## {heading}\n{sec['text']}")

    if compact and not sections:
        # Fallback: No section detected via keyword (e.g., due to non-standard heading naming) -> better to use the first and last two sections than to leave it empty.
        all_sections = parsed["sections"]
        fallback = (
            all_sections[:2] + all_sections[-2:]
            if len(all_sections) > 4
            else all_sections
        )
        for sec in fallback:
            heading = sec["heading"] or "(ohne Überschrift)"
            parts.append(f"\n## {heading}\n{sec['text']}")

    return "\n".join(parts)


def main():
    parser = argparse.ArgumentParser(
        description="Parse TEI-XML into structured plain text"
    )
    parser.add_argument(
        "--input", required=True, help="Folder containing the .tei.xml files"
    )
    parser.add_argument("--output", required=True, help="Output folder for .json/.txt")
    parser.add_argument(
        "--mode",
        choices=["compact", "full"],
        default="compact",
        help="'compact': only abstract + sections resembling an introduction/conclusion "
        "(standard, for categorization/problem/solution/research gap). "
        "'full': complete body text.",
    )
    args = parser.parse_args()

    input_dir = Path(args.input)
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    xml_files = sorted(input_dir.glob("*.tei.xml"))
    if not xml_files:
        print(f"No .tei.xml files found in {input_dir}")
        return

    is_compact = args.mode == "compact"
    suffix = ".compact.txt" if is_compact else ".txt"

    char_counts = []
    errors = []

    for xml_path in tqdm(xml_files, desc=f"Parsing TEI-XML ({args.mode})"):
        stem = xml_path.stem.replace(".tei", "")
        try:
            parsed = parse_tei(xml_path)
            text = to_plain_text(parsed, compact=is_compact)

            (output_dir / "json" / f"{stem}.json").write_text(
                json.dumps(parsed, indent=2, ensure_ascii=False), encoding="utf-8"
            )
            (output_dir / f"{stem}{suffix}").write_text(text, encoding="utf-8")

            char_counts.append(len(text))
        except Exception as e:  # noqa: BLE001
            errors.append((xml_path.name, str(e)))

    print(f"\n{len(char_counts)} Paper parsed successfully (Modus: {args.mode}).")
    if char_counts:
        avg = sum(char_counts) // len(char_counts)
        print(
            f"Signs per paper – min: {min(char_counts)}, max: {max(char_counts)}, "
            f"avarage: {avg}"
        )
    if errors:
        print(f"\n{len(errors)} Error:")
        for name, err in errors:
            print(f"  {name}: {err}")


if __name__ == "__main__":
    main()

# py grobid_parse_xml.py --input open_access --output open_access/compact --mode compact
# py grobid_parse_xml.py --input open_access --output open_access/fulltext --mode full

# py grobid_parse_xml.py --input not_open_access --output not_open_access/compact --mode compact
# py grobid_parse_xml.py --input not_open_access --output not_open_access/fulltext --mode full
